apiVersion: v1
kind: Service
metadata:
  name: {{ include "asewardgames.fullname" . }}
  labels:
    {{- include "asewardgames.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: 80
  selector:
    {{- include "asewardgames.selectorLabels" . | nindent 4 }}
